/* Existing Pages UI -> authenticated AWS reservations. No fallback after AWS enablement. */
'use strict';
window.BookingClient=(()=>{
 const root='https://core.thaimaliwan.pl',screen=location.pathname.includes('/rezerwacje/')?'manual':'calendar';
 let enabled=false,pending;
 const errors={TERM_OCCUPIED:'Termin jest zajęty. Odśwież grafik.',STALE_VERSION:'Rezerwacja została zmieniona. Odśwież grafik.',STALE_SCHEDULE:'Brak aktualnego grafiku.',STALE_SOURCE:'Właśnie odświeżono dane. Ponów zapis.',UNKNOWN_SOURCE_STAFF:'Import zawiera nierozpoznaną masażystkę. Zapis zatrzymany.',SOURCE_UNAVAILABLE:'Nie udało się odczytać bieżących wizyt. Spróbuj ponownie.',SOURCE_TOKEN_REQUIRED:'Połącz dotychczasowe źródło rezerwacji.',PHONE_REQUIRED:'Podaj poprawny numer telefonu klienta.',CUSTOMER_NEEDS_REVIEW:'Numer telefonu pasuje do innego lub kilku profili. Sprawdź kartotekę klienta.',PRICE_CHANGED:'Cena zmieniła się. Odśwież formularz.',PRICE_NEEDS_REVIEW:'Usługa wymaga sprawdzenia cennika.',OUTSIDE_SHIFT:'Masażystka nie pracuje w tym terminie.',STAFF_ABSENT:'Masażystka ma wolne w tym terminie.',AUTH_REQUIRED:'Zaloguj się do AWS przyciskiem nad grafikiem.',CONFIG_UNAVAILABLE:'Nie udało się sprawdzić połączenia z AWS. Zapis zatrzymany.'};
 async function initialize(){if(!pending)pending=(async()=>{if(location.hostname!=='astera260.github.io')return;const r=await fetch(root+'/api/reception/calendar/config?screen='+screen,{cache:'no-store'});if(!r.ok)throw Error('CONFIG_UNAVAILABLE');enabled=(await r.json()).bookingsEnabled===true;await ReceptionAuth.initialize();if(enabled){const node=document.createElement('div');node.className='staff-calendar-connection';node.textContent='Rezerwacje ręczne: AWS · Blokady w Booksy ustawiamy osobno';(document.querySelector('.ui-r1')||document.body).prepend(node);const state=document.getElementById('zapisStatus');if(state)state.textContent='Rezerwacje ręczne · zapis do AWS po zalogowaniu';}})();return pending;}
 async function send(action,payload){await initialize();if(!enabled)throw Error('AWS_DISABLED');if(!ReceptionAuth.authenticated())throw Error('AUTH_REQUIRED');const r=await fetch(root+'/api/reception/bookings/'+action,{method:'POST',headers:{...ReceptionAuth.headers(),'Content-Type':'application/json'},body:JSON.stringify({...payload,sourceToken:localStorage.getItem('asteraReadToken')||''}),signal:AbortSignal.timeout(45000)});const d=await r.json();if(!r.ok)throw Error(d.error||'AWS_UNAVAILABLE');return d;}
 async function command(p){try{return await send('command',Object.fromEntries(Object.entries(p).map(([k,v])=>[k,String(v)])));}catch(e){return{ok:false,error:errors[e.message]||e.message,uncertain:e.name==='TimeoutError'||e instanceof TypeError};}}
 return{initialize,enabled:()=>enabled,read:p=>send('read',p),command,message:e=>errors[e]||e};
})();
